プラン詳細ページの作成
Haru-Kobayashi073/Shibuya-Buddy pull request #101
Opened 2024-12-29 13:31 UTC by PenginPenPen

## 対応したこと

プラン詳細ページの作成
mapで定義されたplanの情報を表示
Placeが格納されたリストを使いプランの表示

## 残タスク

PlaceCardの数字の下の線の長さが固定値
ExpadedやLayerbuilderを使ってウィジェットの長さを取得しても解決せず。

## 画面キャプチャ
### 画像のリンクが切れている時の表示
<img src="https://github.com/user-attachments/assets/864fbcb4-b93a-4e3d-abfc-a5221153b0ba" width="50%" />
### 通常表示
<img src="https://github.com/user-attachments/assets/07121e87-5df0-450b-92fe-1fbb3fc380f4" width="50%" />

2024-12-29 16:35 UTC, Haru-Kobayashi073 requested changes
あとは、ざけちゃんがさっき言ってた、SliverAppbarを使ってみて修正して欲しい！

2024-12-29 16:35 UTC, Haru-Kobayashi073 commented on lib/presentation/plan_detail/components/plan_header.dart
> +class PlanHeader extends StatefulWidget {
StatefulWidgetになってるからStatelessに直してあげてほしい！

2024-12-29 16:35 UTC, Haru-Kobayashi073 commented on lib/presentation/plan_detail/components/plan_header.dart
> +            image: NetworkImage(widget.imageUrl.toString()),
最新のdevelopブランチを取り込むと、PresistentCachedNetworkImageっていうウィジェットがあるからそれを使うのがおすすめ

2024-12-29 16:35 UTC, Haru-Kobayashi073 commented on lib/presentation/plan_detail/components/plan_header.dart
> +            image: NetworkImage(widget.imageUrl.toString()),
エラー処理も共通化してあるから、書かなくて済むようになるはず

2024-12-29 16:35 UTC, Haru-Kobayashi073 commented on lib/presentation/plan_detail/plan_detail_page.dart
> +class PlanInfo {
これはPlanクラスをそのまま使うことはできない？

2024-12-29 16:35 UTC, Haru-Kobayashi073 commented on lib/presentation/plan_detail/components/left_icon_wide_button.dart
> +import 'package:flutter/material.dart';
このウィジェットを使う代わりにWideButton.iconを使ってほしい！
ただ、WideButton.iconを使うとiconが中央のテキストにくっついてしまうと思うから、WideButton.iconをアイコンとテキストが離れるように書き直してくれない？🙏

2024-12-30 10:37 UTC, PenginPenPen commented
![キャプチャ](https://github.com/user-attachments/assets/cc2d2817-a347-4599-b42d-614ed017577c)

2024-12-30 13:23 UTC, Haru-Kobayashi073 requested changes
@PenginPenPen 
修正お願いします！

2024-12-30 13:23 UTC, Haru-Kobayashi073 commented on lib/infrastructure/user/user_data_source.dart
> +        .doc('n2lEinZTRIVzcKyMR2nTWrZJUy52')
idがハードコードされているので修正してください！

2024-12-30 13:23 UTC, Haru-Kobayashi073 commented on lib/presentation/components/place_card.dart
> +            Offstage(
このファイルはOffstateウィジェットの部分以外変更していないはずなので、コンフリクトミスしてます！

2024-12-30 13:23 UTC, Haru-Kobayashi073 commented on lib/presentation/plan_detail/components/plan_header.dart
> +    required this.title,
Planモデルのみを直接受け取る形にするとスッキリするかも！

2024-12-30 13:23 UTC, Haru-Kobayashi073 commented on lib/domain/entities/place.dart
> -    required Coordinate coordinate,
このファイルもコンフリクト修正ミスかな？
戻して欲しい！

2024-12-30 13:23 UTC, Haru-Kobayashi073 commented on lib/presentation/plan_detail/plan_detail_page.dart
> +                            icon: const Icon(Icons.pin_drop_outlined),
アイコンが白色なのでデザイン通りに頼んだ！

2024-12-30 13:23 UTC, Haru-Kobayashi073 commented on lib/presentation/plan_detail/components/plan_header.dart
> +    return Column(
一番外側のColumnウィジェットはPaddingウィジェットしか囲んでいないので、一番外のColumnウィジェットは削除しましょう！

2024-12-30 13:23 UTC, Haru-Kobayashi073 commented on lib/presentation/components/wide_button.dart
> +        child: ElevatedButton(
ごめんかなりデザイン変わっちゃってるからこれは別issueで対応しよう！
申し訳ないんだけど、元に戻して欲しい！

2024-12-30 13:23 UTC, Haru-Kobayashi073 commented on lib/presentation/plan_detail/components/plan_header.dart
> +                ),
説明文と作成日の間に空白がないかも

```suggestion
                ),
                const SizedBox(height: 8)
```

2024-12-30 14:32 UTC, Haru-Kobayashi073 requested changes
一点お願い！

2024-12-30 14:32 UTC, Haru-Kobayashi073 commented on lib/domain/entities/place.dart
> +    List<String>? tags,
このファイルからは変更が出ないはずなので、出なくなるようにしてください！
また、make runnerコマンドも回してください！

2024-12-30 14:34 UTC, Haru-Kobayashi073 requested changes

2024-12-30 14:34 UTC, Haru-Kobayashi073 commented on lib/presentation/plan_detail/components/plan_header.dart
> +  final Place place;
Placeクラスではなく、Planクラスです！

2024-12-30 15:39 UTC, Haru-Kobayashi073 requested changes
ラスト一点

2024-12-30 15:39 UTC, Haru-Kobayashi073 commented on lib/domain/entities/topic.dart
> +    String? thumbnailUrl,
今回のPRでは必要がないかもしれないけれど、必須にしておきたいので、requiredにしてください！

2024-12-30 15:39 UTC, Haru-Kobayashi073 commented on lib/domain/entities/topic.dart
> +    String? thumbnailUrl,
make runner忘れずに

2024-12-30 15:39 UTC, Haru-Kobayashi073 commented on lib/domain/entities/topic.dart
> +    String? thumbnailUrl,
今回Topicクラスを使う場所では、thumbnailUrlは空で大丈夫

2024-12-30 15:43 UTC, Haru-Kobayashi073 approved these changes
LGTM!

2024-12-30 15:44 UTC, merged