課金詳細画面を実装
Haru-Kobayashi073/Shibuya-Buddy pull request #103
Opened 2024-12-29 18:21 UTC by shi0n0

## 対応したこと
- ルーティング
- 料金プラン表
- グレードごとの機能表
- 課金選択モーダル
- 多言語化対応

## 関連資料
[StackOverFlow](https://stackoverflow.com/questions/71737194/sliver-app-bar-with-transparent-background)
[ヒヨコプログラミング](https://hiyoko-programming.com/2190/)
[Flutter公式 - Table](https://api.flutter.dev/flutter/widgets/Table-class.html)
[ChatGPT](chatgpt.com)

## 残タスク

- [ ] プレミアムにアップグレードを押下した際の課金機能との結合

## 画面キャプチャ
<div style="display: flex; gap: 10px; justify-content: center; align-items: center;">
  <img src="https://github.com/user-attachments/assets/da5e6f85-d9f9-4463-a433-9a6bee921373" alt="Screenshot 1" width="45%" />
  <img src="https://github.com/user-attachments/assets/5d908d8f-b5e6-46c8-8f12-089a91bbc0d8" alt="Screenshot 2" width="45%" />
</div>

2024-12-29 19:59 UTC, Haru-Kobayashi073 requested changes
一旦1回目のレビュー以上で🙏

2024-12-29 19:59 UTC, Haru-Kobayashi073 commented on lib/presentation/bill_details/bill_details_page.dart
> +                  background: Image.asset(imagePath, fit: BoxFit.cover),
せっかく`assets.gen.dart`ファイルを生成してるので、文字列をハードコードせず、安全に呼び出してあげましょう！

```suggestion
                  background: Image.asset(Assets.images.billingHeader, fit: BoxFit.cover),
```

2024-12-29 19:59 UTC, Haru-Kobayashi073 commented on lib/presentation/bill_details/bill_details_page.dart
> +                        Navigator.pop(context);
go_routerを使用した場合のPopは、以下のような感じになる！
```suggestion
                        context.pop();
```

2024-12-29 19:59 UTC, Haru-Kobayashi073 commented on lib/presentation/bill_details/components/bottom_modal.dart
> +class _BottomModalState extends State<BottomModal> {
このくらいの状態変化なら、StatefulWidgetを使用せず、HookWidgetとuseStateで書いて欲しいけれど、今回はすぐに書き換えが起きそうなので一旦よし！

2024-12-29 19:59 UTC, Haru-Kobayashi073 commented on lib/presentation/bill_details/components/bottom_modal.dart
> +class PlanCard extends StatelessWidget {
現状PlanCardというコンポーネントがすでにあるので、こちらを変えてもらえると嬉しい...!
例えば↓(これ以外ももちろん可)
```suggestion
class PurchaseItemCard extends StatelessWidget {
```

2024-12-29 19:59 UTC, Haru-Kobayashi073 commented on lib/presentation/bill_details/components/bottom_modal.dart
> +class PlanCard extends StatelessWidget {
ワンチャンファイル分けてもいいかも？

2024-12-29 19:59 UTC, Haru-Kobayashi073 commented on lib/presentation/components/wide_button.dart
> +  factory WideButton.gradient({
いいね〜

2024-12-29 19:59 UTC, Haru-Kobayashi073 commented on lib/presentation/bill_details/components/plan_table.dart
> +                            ),
Columnウィジェットごといらないかも？
```suggestion
                                Text(
                                  t.billDetailsPage.pricingPlan.details
                                      .premiumPrice.lifetimePrice,
                                  style: planTextStyle,
                                ),
```

2024-12-29 19:59 UTC, Haru-Kobayashi073 commented on lib/presentation/bill_details/components/plan_table.dart
> +                            ),
一応ローカルで消して試したけれど、なくても大丈夫そう

2024-12-29 19:59 UTC, Haru-Kobayashi073 commented on lib/presentation/bill_details/components/plan_table.dart
> +                    color: AppColor.yellow200,
好みの問題だけど、俺はネストが深いとみづらくなると思ってるので、なるべく子ウィジェットのプロパティで済ませられることは済ませたい！
ので、ClipRRectを削除して、borderRadiusをContainerに直接適用することもできることを書いておきます！

```suggestion
                    decoration: const BoxDecoration(
                    borderRadius: BorderRadius.only(
                      bottomRight: Radius.circular(8),
                    ),
                    color: AppColor.yellow200,
                  ),
```

2024-12-29 19:59 UTC, Haru-Kobayashi073 commented on lib/presentation/bill_details/components/plan_table.dart
> +                    color: AppColor.yellow200,
他のClipRRectウィジェットを使用している部分も同様！

2024-12-29 19:59 UTC, Haru-Kobayashi073 commented on lib/presentation/bill_details/components/grade_based_features.dart
> +        textStyle.copyWith(fontSize: 14, fontWeight: FontWeight.bold);
この二つのTextStyleの変数は、`_buildFeatureTable`メソッド内でしか参照あれていないので、メソッドの引数が増え複雑になるよりかは、メソッド内で変数を定義しても良いかなと思った！

```suggestion
```

2024-12-29 19:59 UTC, Haru-Kobayashi073 commented on lib/presentation/bill_details/components/grade_based_features.dart
> +    return ClipRRect(
ここのClipRRectウィジェットも同様！

2024-12-30 02:48 UTC, shi0n0 commented on lib/presentation/bill_details/bill_details_page.dart
> +                  background: Image.asset(imagePath, fit: BoxFit.cover),
使うの忘れてた...ありがとうDone！

2024-12-30 02:48 UTC, shi0n0 commented on lib/presentation/bill_details/bill_details_page.dart
> +                        Navigator.pop(context);
Done!

2024-12-30 02:48 UTC, shi0n0 commented on lib/presentation/bill_details/components/bottom_modal.dart
> +class _BottomModalState extends State<BottomModal> {
一応HookWidgetとuseState使った実装に変えてみたんだけど見てみてください！

2024-12-30 02:49 UTC, shi0n0 commented on lib/presentation/bill_details/components/bottom_modal.dart
> +class PlanCard extends StatelessWidget {
ファイル分けて名前変えました！Done!

2024-12-30 02:49 UTC, shi0n0 commented on lib/presentation/bill_details/components/plan_table.dart
> +                            ),
こちらも確認して削除しても変わらなかったので削除しました！ありがとう！Done!

2024-12-30 02:55 UTC, shi0n0 commented on lib/presentation/bill_details/components/plan_table.dart
> +                    color: AppColor.yellow200,
ClipRRect使用している場所をBoxDecorationに移管しました！Done!

2024-12-30 02:56 UTC, shi0n0 commented on lib/presentation/bill_details/components/grade_based_features.dart
> +    return ClipRRect(
OKありがとう！Done!

2024-12-30 03:03 UTC, shi0n0 commented on lib/presentation/bill_details/components/grade_based_features.dart
> +        textStyle.copyWith(fontSize: 14, fontWeight: FontWeight.bold);
何故かheaderStyleがAppTextStyle使ってなかったので修正したのと、二つの変数は_buildFeatureTableメソッド内の定義に移管しました！Done!

2024-12-30 03:05 UTC, shi0n0 commented on lib/presentation/components/wide_button.dart
> +  factory WideButton.gradient({
ヨシ！factoryまともに使ったこと無かったけど便利だね

2024-12-30 03:48 UTC, Haru-Kobayashi073 approved these changes
LGTM!!
ナイス実装

2024-12-30 05:09 UTC, merged