プラン作成ページの実装
Haru-Kobayashi073/Shibuya-Buddy pull request #86
Opened 2024-12-15 11:43 UTC by shi0n0

## 対応したこと
- UI類
  - カスタムテキストフィールドを作成(custom_text_field)
  - タグのとの連携に使用するテキストフィールドを作成(topic_chip_field)
  - タグ(Chips)コンポーネントの作成(topic_chip_field)
  - CupertionoDatePickerでの日付選択モーダルの実装()
  - 汎用選択モーダルの実装(selection_modal)
  - 日時選択のコンポーネントを作成(custom_cupertino_date_picker)
  - ホームから遷移するためのfloatingAcitonButtonを作成

- ファイル構造
  - NotifierにてRIverPodを使用し状態管理/UIの操作等
  - Stateにてクラス/フィールド作成
  - pageにてUIを構築
  - /componentsにページ独自のコンポーネントを配置

- 共通
  - Freezedでのクラス作成,保証(create_plan_state.dart)
  - RiverPodでの状態状態管理(create_plan_notifier.dart)
  

## 関連資料
- [DevelopersIO - Chipsの種類について](https://dev.classmethod.jp/articles/introduction_flutter_chips/)
- [RiverPod](https://pub.dev/packages/riverpod)
- [Freezed](https://pub.dev/packages/freezed)
- [Freezedを学ぼう！](https://zenn.dev/sae_eng/articles/ed68107fdae18d)
- [Modal Bottom Sheet で綺麗なメニューを爆速で作る](https://zenn.dev/kazuki23/articles/ff79dad378c2b3)
- [IOS風のDatePickerを表示するには？](https://qiita.com/kominato_slj/items/2be71354343f1fb20ad6)
- [CupertinoDatePickerの日時を操作する](https://qiita.com/mkosuke/items/f9a3f099be264491d106)
- [Fluter CupertinoDatePicker Widget](https://www.youtube.com/watch?v=uL09CPiM8Ds)
- [Flet CupertionoDatePicker](https://flet.dev/docs/controls/cupertinodatepicker/)
- [TECHRISE](https://tech-rise.net/flutter-ios-style-cupertino-widgets/)
- [[How to change CupertinoDatePicker dateFormat?](https://stackoverflow.com/questions/74917791/how-to-change-cupertinodatepicker-dateformat)](https://stackoverflow.com/questions/74917791/how-to-change-cupertinodatepicker-dateformat)
- [[How to change CupertinoDatePicker display language?](https://stackoverflow.com/questions/53662917/how-to-change-cupertinodatepicker-display-language)](https://stackoverflow.com/questions/53662917/how-to-change-cupertinodatepicker-display-language)
- [All - ChatGPT](chatgpt.com)

## 残タスク

- [ ] AIに伝えるボタンを押下したときの機能実装
- [ ] 全てのセクションにおいての選択肢の追加

## 画面キャプチャ
<table>
  <tr>
    <td>
      <p>日本語</p>
         <video src="https://github.com/user-attachments/assets/dafb28bb-8cb0-4a28-8ecc-c4b47d200861" controls style="max-width: 100%;"></video>
    </td>
    <td>
      <p>英語</p>
      <video src="https://github.com/user-attachments/assets/e6756cff-0308-4ff5-bb70-8c85206bc408" controls style="max-width: 100%;"></video>
    </td>
    <td>
      <p>簡体字</p>
      <video src="https://github.com/user-attachments/assets/fe8efeb5-9886-4fb9-9ab6-d26f44793635" controls style="max-width: 100%;"></video>
    </td>
    <td>
      <p>繁体字</p>
      <video src="https://github.com/user-attachments/assets/cdab7b0e-9761-4fcd-a7ae-aca32bc62616" controls style="max-width: 100%;"></video>
    </td>
  </tr>
</table>

2024-12-19 18:45 UTC, Haru-Kobayashi073 requested changes
@shi0n0 
時間をかけていただけあって、めっちゃ完成度高かった！！！！
コメントするところもあまりなし！

ただ、TextEditingControllerがView側で複雑化している点に関しては、なんとかしたいと思っちゃうよね

一旦確認お願いします！

2024-12-19 18:45 UTC, Haru-Kobayashi073 commented on lib/utils/routes/app_router.dart
> +final createPlanNavigatorKey =
ここは使用していなさそうなので消しましょう！
```suggestion

```

2024-12-22 10:16 UTC, shi0n0 commented on lib/utils/routes/app_router.dart
> +final createPlanNavigatorKey =
done

2024-12-22 10:16 UTC, shi0n0 commented on lib/presentation/create_plan/components/custom_cupertino_date_picker.dart
> +                      color: AppColor.black,
done

2024-12-22 10:16 UTC, shi0n0 commented on lib/presentation/create_plan/components/selection_modal.dart
> +      padding: const EdgeInsets.all(16),
done

2024-12-22 10:16 UTC, shi0n0 commented on lib/presentation/create_plan/components/custom_cupertino_date_picker.dart
> +  final TextEditingController targetController;
done

2024-12-22 10:17 UTC, shi0n0 commented on lib/presentation/create_plan/create_plan_state.dart
> +    @Default('') String numberOfPeople,
消し忘れです！3つとも使用していないので削除しました！

2024-12-22 10:17 UTC, shi0n0 commented on lib/presentation/create_plan/components/selection_modal.dart
> +                return GestureDetector(
done!記述力すごく減った！

2024-12-22 10:18 UTC, shi0n0 commented on lib/presentation/create_plan/components/selection_modal.dart
> +                    leading: isSingleSelect
Done!

2024-12-22 10:18 UTC, shi0n0 commented on lib/presentation/create_plan/create_plan_notifier.dart
> +  void toggleSelection(SelectionField field, String item) {
言うとおりですね！最初から頭の中で道すじを作れていればこういうことは起こらないのに...
とにかくDoneです！

2024-12-22 13:05 UTC, Haru-Kobayashi073 approved these changes
LGTM!

2024-12-22 13:20 UTC, merged